Repository acm-ucr/undecided, pull requests merged in 2023-10, with the labels that each got.

#19 added tailwind colors
  tailwind.config.js
Labels: Ready to Review, Repository

#20 Updated bg color layout
  src/app/layout.js
Labels: Ready to Review

#22 Need feedback on button transition
  src/app/page.js
  src/components/Button.jsx
  src/data/Button.js
  tailwind.config.js
Labels: Ready to Review

#21 created profile header
  src/app/profile/page.js
  src/components/profile/header.jsx
  tailwind.config.js
Labels: Ready to Review, Profile

#26 added landing page
  src/app/page.js
  src/components/landing/Landing.jsx
Labels: Ready to Review

#29 Create Select Component
  src/components/Select.jsx
Labels: Do Not Merge, Dashboard

#23 create register splash
  src/components/register/Splash.jsx
Labels: Do Not Merge, Register

#24 Add navigation bar
  src/app/layout.js
  src/components/Navigation.jsx
Labels: Do Not Merge, Navigation
